version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_PLATFORM: win32

install:
   - git submodule update --init --recursive

before_build:
  # Build dependencies
   - cmd: ./install_dependency.bat
   - cmd: mkdir build
   - cmd: cd build
   - cmd: cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_GENERATOR_PLATFORM=%CMAKE_PLATFORM%
   - cmd: cd ..


build_script:
   - cmake --build build
