version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_ARCHITECTURE: Win32

install:
   - git submodule update --init --recursive

before_build:
  # Build dependencies

   - cmd: mkdir dependency
   - cmd: cd public

   - cmd: cd yaml-cpp
   - cmd: mkdir build
   - cmd: cd build
   - cmd: cmake -G "%CMAKE_GENERATOR%" -A %CMAKE_ARCHITECTURE% -DYAML_CPP_BUILD_TESTS=OFF -DYAML_BUILD_SHARED_LIBS=ON ../
   - cmd: cmake --build . --config Release
   - cmd: cmake --install . --prefix ../../../dependency
   - cmd: cd ..
   - cmd: rm -rf build


   - cmd: cd ..

   - cmd: cd glfw
   - cmd: mkdir build
   - cmd: cd build

   - cmd: cmake -G "%CMAKE_GENERATOR%" -A %CMAKE_ARCHITECTURE% -DBUILD_SHARED_LIBS=ON ../
   - cmd: cmake --build . --config Release
   - cmd: cmake --install . --prefix ../../../dependency
   - cmd: rm -rf build

   - cmd: cd ../../../

   - cmd: ./install_dependency.bat
   - cmd: mkdir build
   - cmd: cd build
   - cmd: cmake -G "%CMAKE_GENERATOR%" -A %CMAKE_ARCHITECTURE% ..
   - cmd: cd ..


build_script:
   - cmake --build build
