model:
  type: cpu-ray-tracing
  pipeline: whitted
  jitter-sample-amount: 0
  max-depth: 2

scene:
  material:
    - name: lambertian.red
      type: lambertian
      ambient-color: [0.3, 0.3, 0.3]
      diffuse-color: [0.8, 0.2, 0.2]
      specular-color: [0.07, 0.03, 0.1]
      specular-exp: 0.0
      roughness: 0.0
    - name: lambertian.green
      type: lambertian
      ambient-color: [0.3, 0.3, 0.3]
      diffuse-color: [0.2, 0.8, 0.2]
      specular-color: [0.03, 0.07, 0.1]
      specular-exp: 0.0
      roughness: 0.0
    - name: lambertian.white
      type: lambertian
      ambient-color: [0.3, 0.3, 0.3]
      diffuse-color: [0.5, 0.5, 0.5]
      specular-color: [0.05, 0.05, 0.05]
      specular-exp: 0.0
      roughness: 0.0
    - name: dielectric.ball.1
      type: dielectric
      reference-index: 0.7
    - name: area.light.1
      type: area-light
      position: [-0.3, 2.5, 5.0]
      color: [1.0, 1.0, 1.0]
      u-direction: [0.0, 0.0, 1.0]
      v-direction: [0.6, 0.0, 0.0]
  mesh:
    - name: box
      type: triangle-group
      vertices:
        - [-6.0, -6.0, 0.0]
        - [-6.0, 6.0, 0.0]
        - [6.0, 6.0, 0.0]
        - [6.0, -6.0, 0.0]
        - [-6.0, -6.0, 12.0]
        - [-6.0, 6.0, 12.0]
        - [6.0, 6.0, 12.0]
        - [6.0, -6.0, 12.0]
      individual_triangle: true
      bvh_acceleration: true
      triangles:
        - name: triangle.up.1
          material: lambertian.white
          indices: [1, 2, 5]
        - name: triangle.up.2
          material: lambertian.white
          indices: [2, 6, 5]
        - name: triangle.down.1
          material: lambertian.white
          indices: [0, 4, 3]
        - name: triangle.down.2
          material: lambertian.white
          indices: [3, 4, 7]
        - name: triangle.left.1
          material: lambertian.red
          indices: [0, 1, 4]
        - name: triangle.left.2
          material: lambertian.red
          indices: [1, 5, 4]
        - name: triangle.right.1
          material: lambertian.green
          indices: [3, 7, 2]
        - name: triangle.right.2
          material: lambertian.green
          indices: [2, 7, 6]
        - name: triangle.back.1
          material: lambertian.white
          indices: [4, 5, 7]
        - name: triangle.back.2
          material: lambertian.white
          indices: [7, 5, 6]
    - name: area.light
      type: triangle-group
      vertices:
        - [-0.3, 2.5, 5.0]
        - [0.3, 2.5, 5.0]
        - [0.3, 2.5, 6.0]
        - [-0.3, 2.5, 6.0]
      individual_triangle: true
      bvh_acceleration: true
      triangles:
        - name: area.triangle.up.1
          material: area.light.1
          indices: [0, 1, 2]
        - name: area.triangle.up.2
          material: area.light.1
          indices: [0, 2, 3]
  object:
    - group:
      - type: geometry-group
        geometry:
          - instance-name: box
          - instance-name: area.light


viewer:
  position: [0.0, 0.0, 0.1]
  direction: [0.0, 0.0, 1.0]
  up: [0.0, 1.0, 0.0]
  FOV: 45
  resolution: [800, 800]