model:
  type: ray-tracing
  pipeline: whitted

scene:
  light:
    - light.1:
        type: point-light
        position: [0.0, 5.9, 8.5]
        color: [0.3, 0.3, 0.3]
#    area-light:
  material:
    - lambertian.red:
        type: lambertian
        ambient-color: [0.0, 0.0, 0.0]
        diffuse-color: [1.0, 0.2, 0.2]
        specular-color: [0.07, 0.03, 0.1]
        specular-exp: 0.0
        roughness: 0.0
    - lambertian.green:
        type: lambertian
        ambient-color: [0.0, 0.0, 0.0]
        diffuse-color: [0.2, 1.0, 0.2]
        specular-color: [0.03, 0.07, 0.1]
        specular-exp: 0.0
        roughness: 0.0
    - lambertian.white:
        type: lambertian
        ambient-color: [0.0, 0.0, 0.0]
        diffuse-color: [0.5, 0.5, 0.5]
        specular-color: [0.05, 0.05, 0.05]
        specular-exp: 0.0
        roughness: 0.0
    - dielectric.ball.1:
        type: dielectric
        reference-index: 0.7

  object:
    - sphere.1:
        type: sphere
        material: dielectric.ball.1
        position: [0.0, -2.8, 8.0]
        radius: 2.5
    - box:
        type: triangle-group
        vertices:
          - [-6.0, -6.0, 0.0]
          - [-6.0, 6.0, 0.0]
          - [6.0, 6.0, 0.0]
          - [6.0, -6.0, 0.0]
          - [-6.0, -6.0, 12.0]
          - [-6.0, 6.0, 12.0]
          - [6.0, 6.0, 12.0]
          - [6.0, -6.0, 12.0]
        triangles:
          - triangle.up.1:
              material: lambertian.white
              indices: [1, 2, 5]
          - triangle.up.2:
              material: lambertian.white
              indices: [2, 5, 6]
          - triangle.down.1:
              material: lambertian.white
              indices: [0, 3, 4]
          - triangle.down.2:
              material: lambertian.white
              indices: [3, 4, 7]
          - triangle.left.1:
              material: lambertian.red
              indices: [0, 1, 4]
          - triangle.left.2:
              material: lambertian.red
              indices: [1, 4, 5]
          - triangle.right.1:
              material: lambertian.green
              indices: [3, 2, 7]
          - triangle.right.2:
              material: lambertian.green
              indices: [2, 7, 6]
          - triangle.back.1:
              material: lambertian.white
              indices: [4, 7, 5]
          - triangle.back.2:
              material: lambertian.white
              indices: [7, 5, 6]
viewer:
  position: [0.0, 0.0, 0.1]
  direction: [0.0, 0.0, 1.0]
  up: [0.0, 1.0, 0.0]
  FOV: 45
  resolution: [800, 800]